chore: Bump @prisma/client from 4.13.0 to 4.14.1 (#2038)
Bumps
[@prisma/client](https://github.com/prisma/prisma/tree/HEAD/packages/client)
from 4.13.0 to 4.14.1.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/prisma/prisma/releases"><code>@​prisma/client</code>'s
releases</a>.</em></p>
<blockquote>
<h2>4.14.1</h2>
<p>Today, we are issuing the <code>4.14.1</code> patch release.</p>
<h2>Fix in Prisma Client</h2>
<ul>
<li><a
href="https://redirect.github.com/prisma/prisma/issues/19174"><code>@​prisma/client/</code>edge
+ Cloudflare Worker / wrangler = Could not resolve
&quot;os&quot;</a></li>
</ul>
<h2>4.14.0</h2>
<p>🌟 <strong>Help us spread the word about Prisma by starring the repo
or <a
href="https://twitter.com/intent/tweet?text=Check%20out%20the%20latest%20@prisma%20release%20v4.14.0%20%F0%9F%9A%80%0D%0A%0D%0Ahttps://github.com/prisma/prisma/releases/tag/4.14.0">tweeting</a>
about the release.</strong> 🌟</p>
<h2>Request for feedback for Preview features</h2>
<p>We would appreciate your feedback on a handful of <a
href="https://www.prisma.io/docs/about/prisma/releases#preview">Preview
features</a> to help us move them to <a
href="https://www.prisma.io/docs/about/prisma/releases#generally-available-ga">General
Availability</a> soon. The Preview features include:</p>
<ul>
<li><a
href="https://redirect.github.com/prisma/prisma/issues/15835">PostgreSQL
extensions</a></li>
<li><a
href="https://redirect.github.com/prisma/prisma/issues/15837">Extended
where unique</a></li>
<li><a
href="https://redirect.github.com/prisma/prisma/issues/15068">Field
reference support</a></li>
<li><a
href="https://redirect.github.com/prisma/prisma/issues/14377">Order by
Nulls</a></li>
<li><a
href="https://redirect.github.com/prisma/prisma/issues/15069">Count by
filtered relation</a></li>
</ul>
<p>You can test them by enabling the Preview feature in your Prisma
schema and giving them a try already in your Prisma schema, e.g.,
PostgreSQL extensions, or regenerating Prisma Client and trying them in
your queries.</p>
<h2>Highlights</h2>
<h3>Improved Prisma Client startup performance</h3>
<p>For the last couple of months, we've been working hard to improve the
performance of Prisma Client. We also published a blog post on how <a
href="https://www.prisma.io/blog/prisma-and-serverless-73hbgKnZ6t">How
We Sped Up Serverless Cold Starts with Prisma by 9x</a>, which we
recommend you give it a read.</p>
<p>This release continues with the same theme by making the size of the
generated Prisma Client smaller. We have roughly halved the size of
Prisma Client's dependencies.</p>
<h3>More Introspection warnings for unsupported features</h3>
<p>In <a
href="https://github.com/prisma/prisma/releases/tag/4.13.0">4.13.0</a>,
we introduced the first 6 introspection warnings that surface the
existence of these features in your database and link to our
documentation on how to manually work around the Prisma Schema with
unsupported database features.</p>
<p>In this release, we added 3 more introspection warnings for the
following features:</p>
<ul>
<li><a
href="https://redirect.github.com/prisma/prisma/issues/3388">Check
Constraints</a> (MySQL + PostgreSQL)</li>
<li><a
href="https://redirect.github.com/prisma/prisma/issues/17514">Exclusion
Constraints</a></li>
<li><a
href="https://redirect.github.com/prisma/prisma/issues/8135">MongoDB
$jsonSchema</a></li>
</ul>
<p>On introspecting a database using any of these features, you will get
a warning from the Prisma CLI and a comment in your Prisma schema where
the feature is being used. The warning will also contain a link to
instructions on how to manually use the feature.</p>
<h2>Fixes and improvements</h2>
<h3>Prisma Client</h3>
<ul>
<li><a
href="https://redirect.github.com/prisma/prisma/issues/12295">Generator
output <code>client</code> leads to <code>Error: ENOENT: no such file or
directory, open
'.../node_modules/@prisma/client/schema.prisma'</code></a></li>
<li><a
href="https://redirect.github.com/prisma/prisma/issues/17127">DeprecationWarning:
Implicit coercion to integer for exit code is deprecated</a></li>
<li><a
href="https://redirect.github.com/prisma/prisma/issues/18517"><code>thread
'tokio-runtime-worker' panicked at 'internal error: entered unreachable
code: No unsupported field should reach that path',
query-engine\connectors\sql-query-connector\src\model_extensions\scalar_field.rs:70:44</code></a></li>
<li><a
href="https://redirect.github.com/prisma/prisma/issues/18549">jsonProtocol:
<code>in</code> argument of filter types does not accept
scalars</a></li>
</ul>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/prisma/prisma/commit/c4c1ada0ba1bb6abe8895e778734fe78a626bc63"><code>c4c1ada</code></a>
chore: Change shortlink for bundler-investigation on error case (<a
href="https://github.com/prisma/prisma/tree/HEAD/packages/client/issues/19247">#19247</a>)</li>
<li><a
href="https://github.com/prisma/prisma/commit/c76626106ed9aa3abf993defce934e4f3e1778a6"><code>c766261</code></a>
fix(client): remove &quot;os&quot; import in ExitHooks, replacing it
with a static map ...</li>
<li><a
href="https://github.com/prisma/prisma/commit/e1c26c17323931a868bb3517212854b376a58116"><code>e1c26c1</code></a>
chore(deps): update engines to
4.14.0-67.d9a4c5988f480fa576d43970d5a23641aa77...</li>
<li><a
href="https://github.com/prisma/prisma/commit/fffbd79b7a5ebdb6e496e0f90fb1662ccaf43975"><code>fffbd79</code></a>
chore(deps): update engines to
4.14.0-66.20385323b6a30937c33354d7a9f7aeaff981...</li>
<li><a
href="https://github.com/prisma/prisma/commit/29dc956f063e7ccc465f76687a0e9b7c237e3f01"><code>29dc956</code></a>
chore(deps): update engines to
4.14.0-65.b941a1de6ceb719196a59b0e60dcbd00ad51...</li>
<li><a
href="https://github.com/prisma/prisma/commit/5a0f10764c6e841b1debdff7dfde27c7ae14d8f7"><code>5a0f107</code></a>
perf(esbuild): don't keep names during minification (<a
href="https://github.com/prisma/prisma/tree/HEAD/packages/client/issues/19095">#19095</a>)</li>
<li><a
href="https://github.com/prisma/prisma/commit/01626da2cf00ec1fdc1489c150cd51a87641af97"><code>01626da</code></a>
chore(deps): update engines to
4.14.0-64.c694003bd22d0140d0f7911d1ddbdc9d7394...</li>
<li><a
href="https://github.com/prisma/prisma/commit/637ab0c8184e9a93034e81f92f809e9182c105ca"><code>637ab0c</code></a>
chore(deps): update engines to
4.14.0-63.bd111dfeac7de75d9ee9831f1b80ddf35f4e...</li>
<li><a
href="https://github.com/prisma/prisma/commit/6838e4f397a5aaa3ee1341dce04bd82ba139929d"><code>6838e4f</code></a>
chore(deps): update engines to
4.14.0-62.92998a9c18a9f9dbf25ba3f6ba7b1bb784c6...</li>
<li><a
href="https://github.com/prisma/prisma/commit/0339b0807c1aa91a2d36972482fc327f23bbb7ee"><code>0339b08</code></a>
chore(deps): update engines to
4.14.0-58.c03b6915b9eff57212a16840d554da5f6f44...</li>
<li>Additional commits viewable in <a
href="https://github.com/prisma/prisma/commits/4.14.1/packages/client">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=@prisma/client&package-manager=npm_and_yarn&previous-version=4.13.0&new-version=4.14.1)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>