chore: Bump prisma from 4.13.0 to 4.14.1 (#2030)
Bumps [prisma](https://github.com/prisma/prisma/tree/HEAD/packages/cli)
from 4.13.0 to 4.14.1.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/prisma/prisma/releases">prisma's
releases</a>.</em></p>
<blockquote>
<h2>4.14.1</h2>
<p>Today, we are issuing the <code>4.14.1</code> patch release.</p>
<h2>Fix in Prisma Client</h2>
<ul>
<li><a
href="https://redirect.github.com/prisma/prisma/issues/19174"><code>@​prisma/client/</code>edge
+ Cloudflare Worker / wrangler = Could not resolve
&quot;os&quot;</a></li>
</ul>
<h2>4.14.0</h2>
<p>🌟 <strong>Help us spread the word about Prisma by starring the repo
or <a
href="https://twitter.com/intent/tweet?text=Check%20out%20the%20latest%20@prisma%20release%20v4.14.0%20%F0%9F%9A%80%0D%0A%0D%0Ahttps://github.com/prisma/prisma/releases/tag/4.14.0">tweeting</a>
about the release.</strong> 🌟</p>
<h2>Request for feedback for Preview features</h2>
<p>We would appreciate your feedback on a handful of <a
href="https://www.prisma.io/docs/about/prisma/releases#preview">Preview
features</a> to help us move them to <a
href="https://www.prisma.io/docs/about/prisma/releases#generally-available-ga">General
Availability</a> soon. The Preview features include:</p>
<ul>
<li><a
href="https://redirect.github.com/prisma/prisma/issues/15835">PostgreSQL
extensions</a></li>
<li><a
href="https://redirect.github.com/prisma/prisma/issues/15837">Extended
where unique</a></li>
<li><a
href="https://redirect.github.com/prisma/prisma/issues/15068">Field
reference support</a></li>
<li><a
href="https://redirect.github.com/prisma/prisma/issues/14377">Order by
Nulls</a></li>
<li><a
href="https://redirect.github.com/prisma/prisma/issues/15069">Count by
filtered relation</a></li>
</ul>
<p>You can test them by enabling the Preview feature in your Prisma
schema and giving them a try already in your Prisma schema, e.g.,
PostgreSQL extensions, or regenerating Prisma Client and trying them in
your queries.</p>
<h2>Highlights</h2>
<h3>Improved Prisma Client startup performance</h3>
<p>For the last couple of months, we've been working hard to improve the
performance of Prisma Client. We also published a blog post on how <a
href="https://www.prisma.io/blog/prisma-and-serverless-73hbgKnZ6t">How
We Sped Up Serverless Cold Starts with Prisma by 9x</a>, which we
recommend you give it a read.</p>
<p>This release continues with the same theme by making the size of the
generated Prisma Client smaller. We have roughly halved the size of
Prisma Client's dependencies.</p>
<h3>More Introspection warnings for unsupported features</h3>
<p>In <a
href="https://github.com/prisma/prisma/releases/tag/4.13.0">4.13.0</a>,
we introduced the first 6 introspection warnings that surface the
existence of these features in your database and link to our
documentation on how to manually work around the Prisma Schema with
unsupported database features.</p>
<p>In this release, we added 3 more introspection warnings for the
following features:</p>
<ul>
<li><a
href="https://redirect.github.com/prisma/prisma/issues/3388">Check
Constraints</a> (MySQL + PostgreSQL)</li>
<li><a
href="https://redirect.github.com/prisma/prisma/issues/17514">Exclusion
Constraints</a></li>
<li><a
href="https://redirect.github.com/prisma/prisma/issues/8135">MongoDB
$jsonSchema</a></li>
</ul>
<p>On introspecting a database using any of these features, you will get
a warning from the Prisma CLI and a comment in your Prisma schema where
the feature is being used. The warning will also contain a link to
instructions on how to manually use the feature.</p>
<h2>Fixes and improvements</h2>
<h3>Prisma Client</h3>
<ul>
<li><a
href="https://redirect.github.com/prisma/prisma/issues/12295">Generator
output <code>client</code> leads to <code>Error: ENOENT: no such file or
directory, open
'.../node_modules/@prisma/client/schema.prisma'</code></a></li>
<li><a
href="https://redirect.github.com/prisma/prisma/issues/17127">DeprecationWarning:
Implicit coercion to integer for exit code is deprecated</a></li>
<li><a
href="https://redirect.github.com/prisma/prisma/issues/18517"><code>thread
'tokio-runtime-worker' panicked at 'internal error: entered unreachable
code: No unsupported field should reach that path',
query-engine\connectors\sql-query-connector\src\model_extensions\scalar_field.rs:70:44</code></a></li>
<li><a
href="https://redirect.github.com/prisma/prisma/issues/18549">jsonProtocol:
<code>in</code> argument of filter types does not accept
scalars</a></li>
</ul>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/prisma/prisma/commit/72fc5800b0a33bd30aef1b0fa5ede3b68e1bd88f"><code>72fc580</code></a>
refactor(cli): better type and error for tryToReadDataFromSchema (<a
href="https://github.com/prisma/prisma/tree/HEAD/packages/cli/issues/18992">#18992</a>)</li>
<li><a
href="https://github.com/prisma/prisma/commit/ba056968e062558ea21a4407146bf7999e20411d"><code>ba05696</code></a>
fix(generator-helper): Fix DMMF field dbName name and type (<a
href="https://github.com/prisma/prisma/tree/HEAD/packages/cli/issues/18694">#18694</a>)</li>
<li><a
href="https://github.com/prisma/prisma/commit/9f02f22a4f7826661376af1b5d953b1b45c14c52"><code>9f02f22</code></a>
chore(deps): update jest (<a
href="https://github.com/prisma/prisma/tree/HEAD/packages/cli/issues/18250">#18250</a>)</li>
<li><a
href="https://github.com/prisma/prisma/commit/e413a293a22ccce7ccc0f83c4638c8df90f5dd74"><code>e413a29</code></a>
ci: replace jest --verbose logging by --silent (<a
href="https://github.com/prisma/prisma/tree/HEAD/packages/cli/issues/19017">#19017</a>)</li>
<li><a
href="https://github.com/prisma/prisma/commit/cec59d399a13873b7497572040c68b33e5082027"><code>cec59d3</code></a>
refactor: remove some promisify to fs.promises (<a
href="https://github.com/prisma/prisma/tree/HEAD/packages/cli/issues/18990">#18990</a>)</li>
<li><a
href="https://github.com/prisma/prisma/commit/61caee9363976069f6d9701fe3bc34cad9942440"><code>61caee9</code></a>
feat(migrate): Remove &quot;please create new issue&quot;, a residue of
the old `migrat...</li>
<li><a
href="https://github.com/prisma/prisma/commit/56672bed1b7e0ddaa0104453077b2b8f3e84d138"><code>56672be</code></a>
perf(client): Replace <code>chalk</code> with <code>kleur/color</code>
(<a
href="https://github.com/prisma/prisma/tree/HEAD/packages/cli/issues/18900">#18900</a>)</li>
<li>See full diff in <a
href="https://github.com/prisma/prisma/commits/4.14.1/packages/cli">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=prisma&package-manager=npm_and_yarn&previous-version=4.13.0&new-version=4.14.1)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>