chore: bump the prettier group with 1 update (#2314)
Bumps the prettier group with 1 update:
[prettier](https://github.com/prettier/prettier).

Updates `prettier` from 3.1.1 to 3.2.4
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/prettier/prettier/releases">prettier's
releases</a>.</em></p>
<blockquote>
<h2>3.2.4</h2>
<ul>
<li>Fix <code>.eslintrc.json</code> format <a
href="https://redirect.github.com/prettier/prettier/issues/15947">#15947</a></li>
</ul>
<p>🔗 <a
href="https://github.com/prettier/prettier/blob/main/CHANGELOG.md#324">Changelog</a></p>
<h2>3.2.3</h2>
<ul>
<li>Format <code>tsconfig.json</code> file with <code>jsonc</code>
parser <a
href="https://redirect.github.com/prettier/prettier/issues/15927">#15927</a></li>
</ul>
<p>🔗 <a
href="https://github.com/prettier/prettier/blob/main/CHANGELOG.md#323">Changelog</a></p>
<h2>3.2.2</h2>
<p>🔗 <a
href="https://github.com/prettier/prettier/blob/main/CHANGELOG.md#322">Changelog</a></p>
<h2>3.2.1</h2>
<p>🔗 <a
href="https://github.com/prettier/prettier/blob/main/CHANGELOG.md#321">Changelog</a></p>
<h2>3.2.0</h2>
<p><a
href="https://github.com/prettier/prettier/compare/3.1.1...3.2.0">diff</a></p>
<p>🔗 <a href="https://prettier.io/blog/2024/01/12/3.2.0.html">Release
note</a></p>
</blockquote>
</details>
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a
href="https://github.com/prettier/prettier/blob/main/CHANGELOG.md">prettier's
changelog</a>.</em></p>
<blockquote>
<h1>3.2.4</h1>
<p><a
href="https://github.com/prettier/prettier/compare/3.2.3...3.2.4">diff</a></p>
<h4>Fix incorrect parser inference (<a
href="https://redirect.github.com/prettier/prettier/pull/15947">#15947</a>
by <a href="https://github.com/fisker"><code>@​fisker</code></a>)</h4>
<p>Files like <code>.eslintrc.json</code> were incorrectly formatted as
JSONC files.</p>
<!-- raw HTML omitted -->
<pre lang="jsx"><code>// Input
prettier --file-info .eslintrc.json
{ &quot;ignored&quot;: false, &quot;inferredParser&quot;:
&quot;jsonc&quot; }
<p>// Prettier 3.2.4
prettier --file-info .eslintrc.json
{ &quot;ignored&quot;: false, &quot;inferredParser&quot;:
&quot;json&quot; }
</code></pre></p>
<h1>3.2.3</h1>
<p><a
href="https://github.com/prettier/prettier/compare/3.2.2...3.2.3">diff</a></p>
<h4>Throw errors for invalid code (<a
href="https://redirect.github.com/prettier/prettier/pull/15881">#15881</a>
by <a href="https://github.com/fisker"><code>@​fisker</code></a>, <a
href="https://github.com/Josh-Cena"><code>@​Josh-Cena</code></a>, <a
href="https://github.com/auvred"><code>@​auvred</code></a>)</h4>
<!-- raw HTML omitted -->
<pre lang="ts"><code>// Input
1++;
<p>// Prettier 3.2.2
1++;</p>
<p>// Prettier 3.2.3
SyntaxError: Invalid left-hand side expression in unary operation (1:1)
&gt; 1 | 1++;
| ^
</code></pre></p>
<!-- raw HTML omitted -->
<pre lang="ts"><code>// Input
try {} catch (error = 1){}

// Prettier 3.2.2
try {
} catch (error) {}

// Prettier 3.2.3
SyntaxError: Catch clause variable cannot have an initializer. (1:23)
&lt;/tr&gt;&lt;/table&gt; 
</code></pre>
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/prettier/prettier/commit/03822f5b3428ad77781ede5bd41a248b465be3cd"><code>03822f5</code></a>
Release 3.2.4</li>
<li><a
href="https://github.com/prettier/prettier/commit/1cd4d9c1605e7344e6c0735c1c6cb51ad620b01d"><code>1cd4d9c</code></a>
Fix JSONC filenames list (<a
href="https://redirect.github.com/prettier/prettier/issues/15947">#15947</a>)</li>
<li><a
href="https://github.com/prettier/prettier/commit/6c6a332171f590a38c369673662d1a5baf765167"><code>6c6a332</code></a>
Spellcheck</li>
<li><a
href="https://github.com/prettier/prettier/commit/75ec1f792123f42f943fad605236d14a7b02f8c1"><code>75ec1f7</code></a>
Fix lock file</li>
<li><a
href="https://github.com/prettier/prettier/commit/dda00cdd1d602e6034d0dbdac7ee84fc3b32f3a9"><code>dda00cd</code></a>
Clean changelog_unreleased</li>
<li><a
href="https://github.com/prettier/prettier/commit/c12e3c67f93d637cacd2e2a2430f97103abe1276"><code>c12e3c6</code></a>
Git blame ignore 3.2.3</li>
<li><a
href="https://github.com/prettier/prettier/commit/4985be553e911fef7d83f3341eb143c443473c58"><code>4985be5</code></a>
Bump Prettier dependency to 3.2.3</li>
<li><a
href="https://github.com/prettier/prettier/commit/38c0d212e78e645f6c64b88fc6a5847013bc837e"><code>38c0d21</code></a>
Update dependents count</li>
<li><a
href="https://github.com/prettier/prettier/commit/42ba4373f47a67a5d50756a76a57b2ce3a5524e5"><code>42ba437</code></a>
Release 3.2.3</li>
<li><a
href="https://github.com/prettier/prettier/commit/99c873d4219f02f684ec8f3d200abee04e9bbe85"><code>99c873d</code></a>
chore(deps): update typescript-eslint to v6.19.0 (<a
href="https://redirect.github.com/prettier/prettier/issues/15939">#15939</a>)</li>
<li>Additional commits viewable in <a
href="https://github.com/prettier/prettier/compare/3.1.1...3.2.4">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=prettier&package-manager=npm_and_yarn&previous-version=3.1.1&new-version=3.2.4)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore <dependency name> major version` will close this
group update PR and stop Dependabot creating any more for the specific
dependency's major version (unless you unignore this specific
dependency's major version or upgrade to it yourself)
- `@dependabot ignore <dependency name> minor version` will close this
group update PR and stop Dependabot creating any more for the specific
dependency's minor version (unless you unignore this specific
dependency's minor version or upgrade to it yourself)
- `@dependabot ignore <dependency name>` will close this group update PR
and stop Dependabot creating any more for the specific dependency
(unless you unignore this specific dependency or upgrade to it yourself)
- `@dependabot unignore <dependency name>` will remove all of the ignore
conditions of the specified dependency
- `@dependabot unignore <dependency name> <ignore condition>` will
remove the ignore condition of the specified dependency and ignore
conditions


</details>

---------

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: Tobias Diez <code@tobiasdiez.de>