chore: Bump @prisma/client from 4.7.0 to 4.8.0 (#1685)
Bumps
[@prisma/client](https://github.com/prisma/prisma/tree/HEAD/packages/client)
from 4.7.0 to 4.8.0.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/prisma/prisma/releases"><code>@​prisma/client</code>'s
releases</a>.</em></p>
<blockquote>
<h2>4.8.0</h2>
<p>🌟 <strong>Help us spread the word about Prisma by starring the repo
or <a
href="https://twitter.com/intent/tweet?text=Check%20out%20the%20latest%20@prisma%20release%20v4.8.0%20%F0%9F%9A%80%0D%0A%0D%0Ahttps://github.com/prisma/prisma/releases/tag/4.8.0">tweeting</a>
about the release.</strong> 🌟</p>
<h2>Highlights</h2>
<h3>Improved serverless experience — smaller engines size</h3>
<p>In this release, we have decreased the size of our engine files by an
average of 50%. The size of the Query Engine used on Debian, with
OpenSSL 3.0.x, for example, went from 39MB to 14MB. We will also remove
some smaller engines to decrease the total size in future versions.</p>
<p>Additionally, we have started optimizing how the Prisma schema is
loaded in Prisma Client. You should notice a considerable improvement
when executing the first query if you're working with a bigger schema
with many models and relations.</p>
<p>We will continue investing in this direction in the next releases and
further improve the experience with Prisma and serverless
environments.</p>
<h3>Multi-schema support for CockroachDB (Preview)</h3>
<p>We're pleased to share that this release adds <a
href="https://www.prisma.io/docs/about/prisma/releases#preview">Preview
support</a> for multi-schema for CockroachDB. 🎉</p>
<p>This release adds support for:</p>
<ul>
<li>Introspecting databases that organize objects in multiple database
schemas</li>
<li>Managing multi-schema database setups directly from Prisma
schema</li>
<li>Generating migrations that are database schema-aware with Prisma
Migrate</li>
<li>Querying across multiple database schemas with Prisma Client</li>
</ul>
<p>If you already have a CockroachDB database using multiple schemas,
you can quickly get up and running set up multiple schemas by:</p>
<ul>
<li>Enabling the Preview feature in the Prisma schema</li>
<li>Defining the schemas in the <code>schemas</code> property in the
<code>datasource</code> block</li>
<li>Introspecting your database using <code>prisma db pull</code></li>
</ul>
<p>You can further evolve your database schema using the multi-schema
Preview feature by using <code>prisma migrate dev</code>.</p>
<p>For further details, refer to our <a
href="https://prisma.io/docs/guides/database/multi-schema">documentation</a>
and let us know what you think in this <a
href="https://github-redirect.dependabot.com/prisma/prisma/issues/15077">GitHub
issue</a>.</p>
<h3>Improved OpenSSL 3.x support</h3>
<p>Prisma now supports OpenSSL 3 builds for Linux Alpine on
<code>x86_64</code> architectures. This particularly impacts users
running Prisma on <code>node:alpine</code> and
<code>node:lts-alpine</code> Docker images. The images are based on an
Alpine version that ships with OpenSSL 3.0.x, which isn’t compatible
with OpenSSL 1.1.x (already supported by Prisma). You can read more
details about it in this GitHub <a
href="https://github-redirect.dependabot.com/prisma/prisma/issues/16553#issuecomment-1353302617">comment</a>.</p>
<p>We also have rewritten our OpenSSL version detection logic, making it
future-proof. We now expect Prisma to support systems running with any
OpenSSL 3 minor versions out of the box.</p>
<h2>Fixes and improvements</h2>
<h3>Prisma</h3>
<ul>
<li><a
href="https://github-redirect.dependabot.com/prisma/prisma/issues/6382"><code>Migrate:
@​dbgenerated with @db.Time(0) keeps generating new
migrations</code></a></li>
<li><a
href="https://github-redirect.dependabot.com/prisma/prisma/issues/14587"><code>Error
parsing attribute &quot;@​@index&quot;: The Gin index field type
</code><code>Uuid</code> has no default operator class.</a></li>
<li><a
href="https://github-redirect.dependabot.com/prisma/prisma/issues/14895">UTF-8
Error: index is not a char boundary</a></li>
<li><a
href="https://github-redirect.dependabot.com/prisma/prisma/issues/16340">Error
in migration engine. Reason: entered unreachable code </a></li>
<li><a
href="https://github-redirect.dependabot.com/prisma/prisma/issues/16546">Regression
in enum default value handling in 4.7.0</a></li>
<li><a
href="https://github-redirect.dependabot.com/prisma/prisma/issues/16547">Regression
in relation field name deduplication</a></li>
<li><a
href="https://github-redirect.dependabot.com/prisma/prisma/issues/16561">multiSchema:
<code>migrate reset</code> only resets first schema</a></li>
<li><a
href="https://github-redirect.dependabot.com/prisma/prisma/issues/16585">Cross
schema reference with foreign key not working in 4.7.0. </a></li>
</ul>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/prisma/prisma/commit/920da7b8d339a05a8368205d930cef9103370ccd"><code>920da7b</code></a>
chore(deps): update engines to
4.8.0-61.d6e67a83f971b175a593ccc12e15c4a757f93...</li>
<li><a
href="https://github.com/prisma/prisma/commit/6f879cc0fa6038fba44c62c0056837ce1dbdb5dc"><code>6f879cc</code></a>
feat(client): Integrate extended where for optional 1:1 relationships
(<a
href="https://github.com/prisma/prisma/tree/HEAD/packages/client/issues/16844">#16844</a>)</li>
<li><a
href="https://github.com/prisma/prisma/commit/b2e52a17d33a18a0c8931bd368d242a7add8da27"><code>b2e52a1</code></a>
chore(deps): update engines to
4.8.0-60.ba103d5412a7750367d2c96449dc2855e9371...</li>
<li><a
href="https://github.com/prisma/prisma/commit/e6e95eae833ed3c2697ff2e43742b33121bed8d2"><code>e6e95ea</code></a>
perf(client): Use dmmf from a running engine (<a
href="https://github.com/prisma/prisma/tree/HEAD/packages/client/issues/16798">#16798</a>)</li>
<li><a
href="https://github.com/prisma/prisma/commit/98945e99e81bc5e0f117219b6f7f104ca423e2d2"><code>98945e9</code></a>
chore(deps): update engines to
4.8.0-59.6990a563b9ce186cbf24954f6bf9de1de06a9...</li>
<li><a
href="https://github.com/prisma/prisma/commit/333f52adc1b23e7002eb30ad85da32a826682922"><code>333f52a</code></a>
fix(client): fix tsc crashes with client extensions (<a
href="https://github.com/prisma/prisma/tree/HEAD/packages/client/issues/16856">#16856</a>)</li>
<li><a
href="https://github.com/prisma/prisma/commit/c7f89fcef242cc159d81bdd3d979af7fa74e2756"><code>c7f89fc</code></a>
chore(deps): update engines to
4.8.0-58.dbe451b723425a3c3d05cbf034f56ef5aa42a...</li>
<li><a
href="https://github.com/prisma/prisma/commit/40e6f5bfd0316333ff9d56c575ed8925a4f6fbd4"><code>40e6f5b</code></a>
chore(deps): update engines to
4.8.0-57.45e4f95ca2d2c726655add68f7af68bfb71f7...</li>
<li><a
href="https://github.com/prisma/prisma/commit/7c33de91ebeb469cfa02564f7846e0ecc1dbe507"><code>7c33de9</code></a>
chore(deps): update engines to
4.8.0-55.118d3203ec113cbe5750f21d81a5a7a8ee9d3...</li>
<li><a
href="https://github.com/prisma/prisma/commit/934e3ee8dd7f1316f745ae7b1ed2e4d40cf6674d"><code>934e3ee</code></a>
chore(deps): update engines to
4.8.0-53.41f99204486e05f244241d6b1b1e4566b5daa...</li>
<li>Additional commits viewable in <a
href="https://github.com/prisma/prisma/commits/4.8.0/packages/client">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=@prisma/client&package-manager=npm_and_yarn&previous-version=4.7.0&new-version=4.8.0)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>